# Generated by Django 5.1.4 on 2024-12-13 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='asggrd',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 13, 13, 40, 2, 837695, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
